### ISSUE TITLE
Cmake cannot find msgpack ( on Windows)

### ISSUE THREAD

**Issue by RnYi** [rohit-px2/nvui#114]
Ran ` cmake -B build . -DCMAKE_TOOLCHAIN_FILE=.\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -GNinja`

--------------------------
<pre>
......
......
 CMake Error at CMakeLists.txt:37 (find_package):
  Could not find a package configuration file provided by "msgpack" with any
  of the following names:

    msgpackConfig.cmake
    msgpack-config.cmake

  Add the installation prefix of "msgpack" to CMAKE_PREFIX_PATH or set
  "msgpack_DIR" to a directory containing one of the above files.  If
  "msgpack" provides a separate development package or SDK, be sure it has
  been installed.
......
......
</pre>
--------------------------
Should I install vcpkg and dependcies for building?

**Comment by rohit-px2** [comment]
Make sure youre using `cmd` as the shell, I was having issues when I was using powershell to run cmake. Dependencies are all installed by vcpkg before the build starts so you don't have to install them yourself. However, since vcpkg builds from source it will take a long time to build the dependencies (on actions it's over 1 hour).
Also if you just want a specific release you can go to the actions tab and download the latest one, the latest master builds are [here](https://github.com/rohit-px2/nvui/actions/runs/1634669927).

**Comment by RnYi** [comment]
> Make sure youre using `cmd` as the shell, I was having issues when I was using powershell to run cmake. Dependencies are all installed by vcpkg before the build starts so you don't have to install them yourself. However, since vcpkg builds from source it will take a long time to build the dependencies (on actions it's over 1 hour). Also if you just want a specific release you can go to the actions tab and download the latest one, the latest master builds are [here](https://github.com/rohit-px2/nvui/actions/runs/1634669927).

Thanks for anserwing.

**Comment by jamylak** [comment]
msgpack issue was solved for me on mac by replacing `msgpack` with `msgpack-cxx` in `CMakeLists.txt`
