### ISSUE TITLE
doubts on properly way to install

### ISSUE THREAD

**Issue by KitCarson03** [rohit-px2/nvui#125]
hi, i'm a windows user and to install nvui i simply extracted the archive and it recognized the various Nv.. commands but when i put the bin directory into the path it doesn't work anymore, the only solution was to put the plugin directory on the nvim configuration folder and that broke the portability of my configuration.
i'm a new neovim user and i find your frontend the best, so have i done something wrong, any suggestion?

**Comment by rohit-px2** [comment]
Hey, thanks for the kind words. I think this should be solved in the latest commit of the master branch, since I've bundled most of the assets into the application and the Vim code is also hard-coded inside (folders are still there because I haven't updated the build script though). Try the build [here](https://github.com/rohit-px2/nvui/actions/runs/1720974110), that should fix the problem.

**Comment by KitCarson03** [comment]
thanks, the new build solved the problem
