### ISSUE TITLE
Some rendering issues

### ISSUE THREAD

**Issue by finnng** [rohit-px2/nvui#30]
I just tried the newest release on Windows 10. Here are some issues, I can't experiment further after that:
- Font is broken
- The status bar is lost
- Is there any way I can speed up the animation?
Otherwise, it's nice, looking for improvement
![image](https://user-images.githubusercontent.com/70201188/131346439-9dd1cbaf-4007-43f8-b13a-0f62cdb3fbd7.png)

**Comment by rohit-px2** [comment]
That's weird, the font should be fine. I think I might know what is going on there though, I'll get a PR up & see if it fixes the problem.

Speeding up the animation can be done by changing the following:
- Scrolling: `:NvuiScrollAnimationDuration {seconds}` e.g. `:NvuiScrollAnimationDuration 0.2`
- Moving: `:NvuiMoveAnimationDuration {seconds}`
- Cursor Moving: `:NvuiCursorAnimationDuration {seconds}`

**Comment by rohit-px2** [comment]
Btw, the defaults are 0.3s for scrolling and cursor moving, and 0.5s for grids moving.

**Comment by JSchrtke** [comment]
I've encountered this as well, it was caused by the windows scaling.
Change the scaling to 100% in the display settings, that worked for me.

As for reproducing this, anything other than 100% causes this issue.
There is a [function in the windows API](https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getscalefactorfordevice) to detect this, but I'm not sure what can be done to mitigate this issue. Other than the workaround of setting the scaling to 100% that is.

**Comment by rohit-px2** [comment]
Hey @JSchrtke, thanks for pointing me to the DPI, I hadn't thought about that! I made a PR #65 to fix this issue, and it fixes the issue for me (when I set a higher DPI and start the app), could you check if that branch fixes this problem / if there are any problems?

**Comment by JSchrtke** [comment]
Alright, just built that branch. Seems fine for 100% and 125% scaling, after that it gets blurry.

100%:
![image](https://user-images.githubusercontent.com/31078741/133296467-857d301b-20f0-4826-bc41-a70a466e67f4.png)
 
125% looks identical to that.
150%, however is a bit blurry:
![image](https://user-images.githubusercontent.com/31078741/133296603-41b7c8c4-58d7-41bc-aa77-c74588b6ffe3.png)

Interestingly enough, 100 and 125 are the same when having an external monitor connected, but on my laptop, 125% looks like 150% on the external screen, so about as blurry as the picture above.

I guess that has to do with the different screens having different DPI's?
Anyway it does look fine now, not like it was fried like before ;)

**Comment by rohit-px2** [comment]
That's a little weird, what I did in #65 was I factored in the DPI to font size calculations, and then used the default DPI in the render target settings (so that they don't stretch the grid bitmaps, which led to the broken font), so switching monitors shouldn't affect the text rendering quality.
If your DPI is at 100%, how does the text look?

**Comment by JSchrtke** [comment]
As said, 100% looks fine.

![image](https://user-images.githubusercontent.com/31078741/133569917-78c90e93-d75f-47b9-b76e-ad07cfae4a82.png)

**Comment by rohit-px2** [comment]
Alright, I don't know what is causing the blurriness right now. I'll merge #65 in and then look into the blurriness as a separate issue. Thanks for the help!
