### ISSUE TITLE
Problem with CJK Font rendering

### ISSUE THREAD

**Issue by Avimitin** [rohit-px2/nvui#81]
![image](https://user-images.githubusercontent.com/30021675/138419961-b8c83b9d-5fe4-4096-ae1d-176ecd530f80.png)

> The upper window is nvui and the lower window is the terminal. What I expect is the font rendered in the terminal output.

I am using the latest commit to build the nvui. The rendering of the Chinese font has shifted down a little. Also, all the word lose their bottom part and don't align with English.

My font setting: `vim.cmd [[set guifont=FiraCode\ Nerd\ Font\ Mono:h12,Source\ Han\ Sans\ CN,Apple\ Color\ Emoji]]
`

**Comment by rohit-px2** [comment]
Hey, thanks for the info.
About the CJK alignment, nothing special is being done for CJK characters, so it's probably a problem with using `QStaticText` to draw the characters. I use QStaticText mainly because you can cache the text after you make it, so it can get reused in redraws (which happens a lot). The text under the cursor was drawn using `QPainter::drawText` which looks like it is drawn at the proper level.
I'll look into some alternatives to QStaticText. Right now I'm working in #82 to fix a lot of text drawing-related issues.

**Comment by Avimitin** [comment]
Yes, it is better than before. Thx for your help. Waiting for merge into the main branch.

![image](https://user-images.githubusercontent.com/30021675/138575371-51483ec3-d8ec-411e-805a-2dfd28e76cd8.png)

**Comment by rohit-px2** [comment]
Nice, #82 has been merged in.
